### ISSUE TITLE
Allowing influxdb to called in https

### ISSUE THREAD

**Issue by rbenhaddou** [vs4vijay/newman-reporter-influxdb#15]
Hey @vs4vijay 

I would like to suggest you adding those following features :

* Allow influx to be called through https protocol

I have actually forked with your repository to add this feature but it would be nice if we can have it directly from yours : 

Here's a proposal : 

in http.service.js
```
const axiosOptions = {
      baseURL: `${this.context.mode === "https" ? "https" : "http"}://${this.context.server}:${this.context.port}`
    };
```
-> It could be done in a different service js file like https.service.js but it would lot of duplicates only to change the protocol

**Comment by vs4vijay** [comment]
@rbenhaddou - Sure, Make sense. Please raise the PR for it.

**Comment by rbenhaddou** [comment]
Done : #17
