### ISSUE TITLE
Allow passing an identifier to influxdb to search for specific report afterwards

### ISSUE THREAD

**Issue by rbenhaddou** [vs4vijay/newman-reporter-influxdb#16]
Hey @vs4vijay 

I would like to suggest you adding this following feature :

* Allow passing an identifier to influxdb to search for specific report afterwards
* 
I have actually forked with your repository to add this feature but it would be nice if we can have it directly from yours : 

Here's a proposal : 

in influxdb.reporter.js
```
this.context.identifier = this.reporterOptions.influxdbIdentifier || this.reporterOptions.identifier;
```

Then used here in request event method : 

```
const data = {
      collection_name: this.options.collection.name, 
      id: this.context.identifier,
      // ....
}
```

**Comment by vs4vijay** [comment]
Hey @rbenhaddou, thanks for the comment. Could you please raise a PR against it. Will try to review and merge.

**Comment by rbenhaddou** [comment]
Done : https://github.com/vs4vijay/newman-reporter-influxdb/pull/17
