### ISSUE TITLE
Any plans to support influxdb 2.0?

### ISSUE THREAD

**Issue by mmbednarz** [vs4vijay/newman-reporter-influxdb#8]
Hi, 
Do you have any plans to support influxdb 2.0?

**Comment by vs4vijay** [comment]
Hey @mmbednarz , I will take a look at it.

**Comment by vs4vijay** [comment]
@mmbednarz @splitt3r - version 2 released. Please check.

PR - #11

**Comment by mmbednarz** [comment]
It looks like it's working fine, thanks a lot for the quick response.
